---
- hosts: "tag_role_manager"
  become: "yes"
  remote_user: "fedora"

  tasks:
  - name: "Initialize Docker Swarm from manager"
    command: "docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}"

  - name: "Register Swarm join token"
    command: "docker swarm join-token -q worker"
    register: swarm_token

  - name: "Establish Swarm join token as a host fact"
    set_fact: swarmtoken="{{ swarm_token.stdout }}"

  - name: "Copy docker-stack.yml to manager"
    copy:
      src: "docker-stack.yml"
      dest: "/home/fedora/docker-stack.yml"
      owner: "fedora"
      group: "fedora"
    tags:
      - "files"

- hosts: "tag_role_worker"
  become: "yes"
  remote_user: "fedora"

  tasks:
  - name: "Join worker nodes to Swarm cluster"
    command: "docker swarm join --advertise-addr {{ ansible_default_ipv4.address }} --token {{ hostvars[groups['tag_role_manager'][0]].swarmtoken }} {{ hostvars[groups['tag_role_manager'][0]].ansible_default_ipv4.address }}:2377"
