---
- hosts: "all"
  sudo: "yes"
  remote_user: "vagrant"
  gather_facts: false

  tasks:
  - name: "Bootstrap node"
    raw: "apt-get install -y python python2.7"

  - name: "Download containerd"
    get_url:
      url: "https://github.com/docker/containerd/releases/download/0.0.5/containerd"
      dest: "/usr/local/bin/containerd"
      mode: "0755"

  - name: "Download containerd-shim"
    get_url:
      url: "https://github.com/docker/containerd/releases/download/0.0.5/containerd-shim"
      dest: "/usr/local/bin/containerd-shim"
      mode: "0755"

  - name: "Download runc"
    get_url:
      url: "https://github.com/docker/containerd/releases/download/0.0.5/runc"
      dest: "/usr/local/bin/runc"
      mode: "0755"

  - name: "Download ctr"
    get_url:
      url: "https://github.com/docker/containerd/releases/download/0.0.5/ctr"
      dest: "/usr/local/bin/ctr"
      mode: "0755"

  - name: "Set properties for downloaded files"
    file:
      path: "{{ item }}"
      owner: "root"
      group: "root"
      mode: "0755"
    with_items:
    - /usr/local/bin/containerd
    - /usr/local/bin/runc
    - /usr/local/bin/ctr
    - /usr/local/bin/containerd-shim
