---
- hosts: "all"
  sudo: "yes"
  remote_user: "vagrant"

  tasks:
  - name: "Install KVM and Libvirt"
    apt:
      state: "present"
      update_cache: "yes"
      name: "{{ item }}"
    with_items:
      - qemu-kvm
      - libvirt-bin
      - git
      - autoconf
      - libtool
      - virtinst
      - linux-headers-3.19.0-49-generic
      - linux-image-3.19.0-49-generic
      - linux-image-extra-3.19.0-49-generic
